### ISSUE TITLE
Out of date repository!

### ISSUE THREAD

**Issue by venok** [cncjs/cncjs-pendant-raspi-gpio#2]
It's look like the repo need to be updated.

pi@raspberrypi:~ $ sudo npm install --location=global cncjs-pendant-raspi-gpio@latest --unsafe-perm --build-from-source

npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to                                                                     the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available                                                                     for older versions (hapi.im/commercial).
npm WARN deprecated topo@1.1.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to t                                                                    he latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available                                                                     for older versions (hapi.im/commercial).
npm WARN deprecated joi@6.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to t                                                                    he latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available                                                                     for older versions (hapi.im/commercial).
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the                                                                     V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your                                                                     dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/cncjs-pendant-raspi-gpio/node_modules/sleep
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory '/usr/local/lib/node_modules/cncjs-pendant-raspi-gpio/node_modules/sleep/build'
npm ERR!   CXX(target) Release/obj.target/node_sleep/sleep.o
npm ERR! make: Leaving directory '/usr/local/lib/node_modules/cncjs-pendant-raspi-gpio/node_modules/sleep/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@12.22.5 | linux | arm
npm ERR! gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/cncjs-pendant-raspi-gpio/node_modules/sleep/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/12.22.5/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/12.22.5',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/12.22.5/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/local/lib/node_modules/cncjs-pendant-raspi-gpio/node_modules/sleep',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! ../sleep.cc:6:11: error: ‘Handle’ has not been declared in ‘v8’
npm ERR!     6 | using v8::Handle;
npm ERR!       |           ^~~~~~
npm ERR! ../sleep.cc: In function ‘void init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
npm ERR! ../sleep.cc:103:53: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
npm ERR!   103 |     Nan::New<FunctionTemplate>(MSleep)->GetFunction());
npm ERR!       |                                                     ^
npm ERR! In file included from /root/.cache/node-gyp/12.22.5/include/node/node.h:67,
npm ERR!                  from ../node_modules/nan/nan.h:60,
npm ERR!                  from ../sleep.cc:2:
npm ERR! /root/.cache/node-gyp/12.22.5/include/node/v8.h:6126:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
npm ERR!  6126 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
npm ERR!       |                                              ^~~~~~~~~~~
npm ERR! /root/.cache/node-gyp/12.22.5/include/node/v8.h:6126:46: note:   candidate expects 1 argument, 0 provided
npm ERR! ../sleep.cc:105:54: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
npm ERR!   105 |     Nan::New<FunctionTemplate>(MUSleep)->GetFunction());
npm ERR!       |                                                      ^
npm ERR! In file included from /root/.cache/node-gyp/12.22.5/include/node/node.h:67,
npm ERR!                  from ../node_modules/nan/nan.h:60,
npm ERR!                  from ../sleep.cc:2:
npm ERR! /root/.cache/node-gyp/12.22.5/include/node/v8.h:6126:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
npm ERR!  6126 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
npm ERR!       |                                              ^~~~~~~~~~~
npm ERR! /root/.cache/node-gyp/12.22.5/include/node/v8.h:6126:46: note:   candidate expects 1 argument, 0 provided
npm ERR! In file included from ../node_modules/nan/nan.h:60,
npm ERR!                  from ../sleep.cc:2:
npm ERR! ../sleep.cc: At global scope:
npm ERR! /root/.cache/node-gyp/12.22.5/include/node/node.h:736:7: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
npm ERR!   736 |       (node::addon_register_func) (regfunc),                          \
npm ERR!       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! /root/.cache/node-gyp/12.22.5/include/node/node.h:770:3: note: in expansion of macro ‘NODE_MODULE_X’
npm ERR!   770 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
npm ERR!       |   ^~~~~~~~~~~~~
npm ERR! ../sleep.cc:109:1: note: in expansion of macro ‘NODE_MODULE’
npm ERR!   109 | NODE_MODULE(node_sleep, init)
npm ERR!       | ^~~~~~~~~~~
npm ERR! make: *** [node_sleep.target.mk:107: Release/obj.target/node_sleep/sleep.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
npm ERR! gyp ERR! System Linux 5.15.32-v7l+
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/local/lib/node_modules/cncjs-pendant-raspi-gpio/node_modules/sleep
npm ERR! gyp ERR! node -v v12.22.5
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-30T09_40_46_850Z-debug-0.log

**Comment by thijstriemstra** [comment]
use npm-check-updates to upgrade the packages:

```console
sudo npm install -g npm-check-updates
cd /path/to/cncjs-pendant-raspi-gpio
ncu -u
npm install
npm install --save inquirer@^8.0.0
```
